const events = [
  {
    id: 1,
    title: "Music Concert",
    date: "2024-12-01",
    time: "19:00",
    location: "City Arena",
    description: "A thrilling live concert featuring top artists.",
    price: "RM50.00",
    image: "https://picsum.photos/300/200?random=1",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "approved",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
  {
    id: 2,
    title: "Tech Conference",
    date: "2024-12-10",
    time: "09:00",
    location: "Convention Center",
    description:
      "Join industry experts for a day of discussions on the latest tech trends.",
    price: "RM120.00",
    image: "https://picsum.photos/300/200?random=2",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "pending",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
  {
    id: 3,
    title: "Art Exhibition",
    date: "2024-12-15",
    time: "11:00",
    location: "Gallery of Arts",
    description: "Explore stunning works of art from emerging artists.",
    price: "RM30.00",
    image: "https://picsum.photos/300/200?random=3",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "pending",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
  {
    id: 4,
    title: "Food Festival",
    date: "2024-12-20",
    time: "12:00",
    location: "Food Plaza",
    description:
      "A food lover's paradise with a variety of local and international cuisines.",
    price: "RM40.00",
    image: "https://picsum.photos/300/200?random=4",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "rejected",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
  {
    id: 5,
    title: "Charity Run",
    date: "2024-12-25",
    time: "07:00",
    location: "Park Grounds",
    description:
      "Run for a cause! Help raise funds for charity while staying fit.",
    price: "RM20.00",
    image: "https://picsum.photos/300/200?random=5",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "approved",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
  {
    id: 6,
    title: "Stand-Up Comedy Night",
    date: "2024-12-30",
    time: "21:00",
    location: "Comedy Club",
    description: "Laugh out loud with the funniest comedians in town.",
    price: "RM60.00",
    image: "https://picsum.photos/300/200?random=6",
    attendees: 250,
    maxCapacity: 300,
    type: "Conference",
    organizer: "John Smith",
    status: "approved",
    category: "Technology",
    schedule: [
      { time: "10:00 AM", activity: "Registration & Welcome Coffee" },
      { time: "10:30 AM", activity: "Keynote Speech: Future of AI" },
      { time: "12:00 PM", activity: "Networking Lunch" },
      { time: "1:30 PM", activity: "Interactive Workshops" },
      { time: "3:30 PM", activity: "Panel Discussion" },
    ],
    speakers: [
      {
        name: "Dr. Sarah Johnson",
        role: "AI Research Lead",
        company: "Tech Corp",
      },
      {
        name: "Prof. Michael Chen",
        role: "Department Head",
        company: "University",
      },
    ],
  },
];

export default events;
